// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuvyxzthamrgspnezvtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1dnl4enRoYW1yZ3NwbmV6dnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzU4MzAsImV4cCI6MjA1NzYxMTgzMH0.VPXZ6zue3LMlLNFqZeND8zsV6FbPu_kmUW4vVHCAmLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);